# Entry point for all system-level (NixOS) configuration.
#
# Each import below owns one concern. Adding a new area of configuration means
# adding a file here rather than growing a single configuration.nix.
{ ... }:

{
  imports = [
    # Generated by `nixos-generate-config`. Filesystems, swap, and the
    # hardware scan. Do not hand-edit.
    ./hardware-configuration.nix

    ./hardware
    ./boot.nix
    ./nix.nix
    ./networking.nix
    ./locale.nix
    ./users.nix
    ./desktop.nix
    ./gnome.nix
    ./hyprland.nix
    ./fonts.nix
    ./shell.nix
    ./gaming.nix
    ./development.nix
    ./packages.nix
  ];

  # The NixOS release this machine was first installed with.
  #
  # This is NOT the version of the system. It pins the on-disk data formats of
  # stateful services (databases, etc.) so that upgrades do not silently
  # migrate them. Changing it on an existing install can break those services.
  # Leave it alone.
  system.stateVersion = "26.05";
}
